# Generated by Django 2.2.10 on 2020-03-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголвок')),
                ('slug', models.CharField(max_length=255, verbose_name='Идентификатор')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Номер в порядке отображения')),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголвок')),
                ('slug', models.CharField(max_length=255, verbose_name='Идентификатор')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Номер в порядке отображения')),
                ('counter', models.BooleanField(default=False, verbose_name='Счетчик товаров')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Еденица измрения')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголвок')),
                ('slug', models.CharField(max_length=255, verbose_name='Идентификатор')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Номер в порядке отображения')),
                ('image', models.ImageField(upload_to='img')),
                ('blank', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServiceGroup', verbose_name='Группа')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unit', verbose_name='Еденица измерения')),
            ],
        ),
    ]
