# Generated by Django 2.2.10 on 2020-03-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
    ]
