# Generated by Django 2.2.10 on 2020-03-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200328_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='image_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='blank',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='index',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер в порядке отображения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Unit', verbose_name='Еденица измерения'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='counter',
            field=models.BooleanField(blank=True, default=False, verbose_name='Счетчик товаров'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='index',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер в порядке отображения'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='Идентификатор'),
        ),
    ]
