# Generated by Django 2.2.10 on 2020-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200328_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainservice',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='index',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер в порядке отображения'),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='Идентификатор'),
        ),
    ]
