# Generated by Django 2.2.10 on 2020-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200328_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainservice',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-num']},
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_l',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_l_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_l_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_m',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_m_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_m_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_s',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_s_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_s_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_xs',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_xs_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image_xs_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='image_l',
            field=models.ImageField(max_length=1000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='image_l_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='image_l_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='image_m',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='image_m_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='image_m_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='image_s',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='image_s_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='image_s_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='image_xs',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='image_xs_size',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='image_xs_url',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='service',
            name='num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
