# Generated by Django 2.2.10 on 2020-03-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200328_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='num',
        ),
        migrations.RemoveField(
            model_name='service',
            name='num',
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image_m',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image_s',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image_xs',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_m',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_s',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_xs',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
