# Generated by Django 2.2.10 on 2020-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200409_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default=0, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
