# Generated by Django 2.2.10 on 2020-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimages',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='commentimages',
            name='image_l',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image_l',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_l',
            field=models.ImageField(editable=False, null=True, upload_to=''),
        ),
    ]
