# Generated by Django 2.2.10 on 2020-04-09 19:56

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200409_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AlterField(
            model_name='commentimages',
            name='image_l',
            field=models.ImageField(editable=False, null=True, upload_to=apps.core.models.imageFilename),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image_l',
            field=models.ImageField(editable=False, null=True, upload_to=apps.core.models.imageFilename),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_l',
            field=models.ImageField(editable=False, null=True, upload_to=apps.core.models.imageFilename),
        ),
    ]
