# Generated by Django 2.2.10 on 2020-04-09 20:46

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200409_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimages',
            name='regen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='regen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='regen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commentimages',
            name='image_l',
            field=models.ImageField(max_length=1000, null=True, upload_to=apps.core.models.imageFilename),
        ),
        migrations.AlterField(
            model_name='commentimages',
            name='image_m',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image_l',
            field=models.ImageField(max_length=1000, null=True, upload_to=apps.core.models.imageFilename),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='image_m',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_l',
            field=models.ImageField(max_length=1000, null=True, upload_to=apps.core.models.imageFilename),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_m',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
