# Generated by Django 2.2.10 on 2020-04-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200409_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimages',
            name='regen',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='regen',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='regen',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
