# Generated by Django 2.2.10 on 2022-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220627_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetable',
            options={'ordering': ['order'], 'verbose_name': 'Цена за услугу', 'verbose_name_plural': 'Список цен'},
        ),
        migrations.AddField(
            model_name='pricetable',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
