# Generated by Django 2.2.10 on 2022-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220627_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='helptext',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='unit',
            field=models.CharField(choices=[('грн.', 'грн.'), ('грн. / шт.', 'грн. / шт.'), ('грн. / куб', 'грн. / куб')], max_length=24, verbose_name='Еденица имерения'),
        ),
    ]
